theme: jekyll-theme-minimal
description: "Understanding peer-to-peer networks." 
#Vires In Numeris Institute.
logo: /assets/img/VIN-logo-bw-5-alata.png
# logo: <a href="index.html"><img src="/assets/img/VIN-logo-bw-5-alata.png">
url: "https://www.viresinnumeris.eu/"
